# Individual Assignment A2

This assessment is marked out of 45 and comprises 40% of the final course mark.

Due by 1700 on Thursday week 12 (1700 on Thursday 11th April).

### Academic misconduct

The assessment is primarily summative in nature. You are expected to be aware of and abide by University policies on academic misconduct.

- [School of Mathematics academic misconduct advice and policies](https://teaching.maths.ed.ac.uk/main/undergraduate/studies/assessment/academic-misconduct)
- [Academic Services academic misconduct information](https://www.ed.ac.uk/academic-services/students/conduct/academic-misconduct)

**This is an individual assignment - do not copy the work of another student.**

If you use any resources (e.g. textbooks or websites) then include appropriate references in your solutions. Course materials do not need to be referenced.

### Markdown

In workshops you have edited Jupyter Notebook "code" cells. Cells can also contain formatted text in "markdown" cells. Some questions ask for further discussion and explanation, which should be provided in appropriate markdown cells. You may wish to use formatting features of markdown cells, although this is optional.

- [Jupyter Notebook: Markdown cells](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Working%20With%20Markdown%20Cells.html)

You can edit markdown cells (e.g the cell initially containing "Discussion for question 1.1" in question 1) by double clicking on them, and render the markdown by selecting the cell and pressing Shift+Return.

### Code commentary

Your code should be extensively commented, with the functionality of each line of code explained with a comment. This is to test your understanding of the code you have written. Up to half of the marks associated with the coding part of a question may be deducted for a missing, incomplete, or inaccurate code commentary.

The following provides an example of the expected level of commenting.

In [ ]:
def is_prime(n):
    """
    Return whether an input positive integer is prime.
    """
    
    if n == 1:        # If n is 1 ...
        return False  # ... then n is not prime
    
    for i in range(2, n):  # Test integers i from 2 to n - 1 inclusive
        if n % i == 0:     # If n is divisible by i ...
            return False   # ... then n is not prime
    # If n is not divisible by any integers from 2 to n - 1 inclusive then n is
    # prime
    return True

### Output and figures

Your code must generate and display all relevant output when run, and all figure formatting must be performed programmatically and not via the interactive plotting interface.

Rerun your code cells after editing your code, to make sure that the output is updated.

### Saving your work

When you edit the notebook, before closing the window/tab make sure to select "File"->"Save and Checkpoint". If using Noteable make sure you also download and keep a copy of the edited file, using "File"->"Download as"->"Notebook".

On lab computers make sure you save edited notebook files in an appropriate location, as otherwise they may be lost when you logout.

- [Information Services: Saving your files](https://www.ed.ac.uk/information-services/computing/desktop-personal/open-access/using/windows7/saving-files)

# Question 1: Area of a triangle

For further relevant discussion on computing the area of a triangle see

* [W. Kahan, Miscalculating area and angles of a needle-like triangle](https://people.eecs.berkeley.edu/~wkahan/Triangle.pdf)

Consider a triangle in $\mathbb{R}^2$ whose vertices have coordinates

$$\left( x_0, y_0 \right) = \left( 1, 1 \right),$$
$$\left( x_1, y_1 \right) = \left( 2 + \frac{1}{\varepsilon}, 2 + \frac{1}{\varepsilon} \right),$$
$$\left( x_2, y_2 \right) = \left( 2 - \frac{2 \varepsilon}{1 + \varepsilon}, 2 + \frac{2 \varepsilon}{1 + \varepsilon} \right),$$
where $\varepsilon$ is some positive real value.

The area of a triangle can be computed using Heron's formula (see section 1 of W. Kahan, referenced above)

$$A = \sqrt{s \left( s - a \right) \left( s - b \right) \left( s - c \right)}~,$$

where $s = \left( a + b + c \right) / 2$, and $a$, $b$, and $c$ are the lengths of the three sides of the triangle.

**1.1** Compute the area of the above triangle using Heron's formula and floating point arithmetic, for different values of $\varepsilon$. Investigate and discuss what happens for small values of $\varepsilon$. Investigate other ways of computing the area of the triangle.

Summarise and explain your results in a discussion of no more than $350$ words.

Your code should be well laid out and easy to understand.  You should make appropriate use of output and plots.

**[10 marks]**

In [ ]:
# Code for question 1.1

### Discussion for question 1.1

# Question 2: Numerical integration

Throughout this question we consider Chebyshev polynomials, and quadrature rules, defined on the reference interval $x \in \left[ -1, 1 \right]$.

**2.1** The degree $p$ Chebyshev points are the roots of the degree $p$ Chebyshev polynomial. Write a function which accepts a positive integer $p$, defining the Chebyshev polynomial degree, and returns the degree $p$ Chebyshev points, as a NumPy vector. You may wish to make use of functionality provided by the following NumPy module

* [NumPy: numpy.polynomials.chebyshev](https://docs.scipy.org/doc/numpy/reference/routines.polynomials.chebyshev.html)

**[2 marks]**

Hint: For $p =3$ the Chebyshev points are $\left\{ -\sqrt{3} / 2, 0, \sqrt{3} / 2 \right\}$.

**2.2** Find the quadrature weights $w_i$ (for $i \in \left\{ 1, \ldots, p \right\}$) associated with interpolatory quadrature rules whose quadrature points $x_i$ are the associated degree $p$ Chebyshev points, for different values of $p$.

Test the quadrature rule obtained for $p = 3$ by using it to approximate

$$\int_{-1}^1 \left( 1 + \cos \left( \pi x \right) \right) {}^2 \mathrm{d}x,$$

and compare the result against the exact value, obtained using SymPy.

**[7 marks]**

**2.3** Investigate the accuracy of the quadrature rules obtained for different values of $p$.

Summarise and explain your results in a discussion of no more than 250 words. 

**[7 marks]**

Your code should be well laid out and easy to understand. You should make appropriate use of displayed output and plots.

In [2]:
import numpy.polynomial.chebyshev as cheb


http://www.exstrom.com/journal/sigproc/chebident.pdf

In [3]:
cheb.chebroots((-1, 1,-1, 1)) # T3 - T2 + T1 - T0 has real roots

array([-5.00000000e-01,  2.52583602e-17,  1.00000000e+00])

In [117]:
cheb.chebfromroots((-9.68245837e-01, -6.85215773e-17,  9.68245837e-01))

array([ 5.55111512e-17, -1.87500001e-01,  5.55111512e-17,  2.50000000e-01])

In [92]:
import math
math.sqrt(3.0)/2.0


0.8660254037844386

In [34]:
import math
math.sqrt(3)/2
math.cos(0.5)
math.pi

3.141592653589793

In [28]:
import numpy

from numpy import polynomial as P

def convertPolytoCheb(pList):
    pListLen = len(pList)
    p = P.Polynomial(range(pListLen))
    c = p.convert(kind=P.Chebyshev)
    return P.chebyshev.poly2cheb(range(pListLen))

ModuleNotFoundError: No module named 'sympy'

In [69]:
# Code for questions 2.1--2.3

def minusLists(t1, t0):
    res1 = []
    i = 0
    for i, v in enumerate(t0):
        res1 += [t1[i] - v]
    for j in range(i+1,len(t1)):
        res1 += [t1[j]]
    return res1
        

# Code for 2.1
def degreePChebyPoly(p):
    if p == 0:
        return [1]
    elif p == 1:
        return [0,1]
    else: 
        pMinus1 = degreePChebyPoly(p-1)
        pMinus2 = degreePChebyPoly(p-2)
        pTerm = [0] + pMinus1  # This is x*pMinus1 - i.e. (1,2) = 2x + 1 ==> (0,1,2) = 2x^2 + X 
        func = lambda x: 2 * x
        pTerm2 = list(map(func, pTerm))
        pTerm3 = minusLists(pTerm2,pMinus2)
        return pTerm3

def degreePChebyPointsWrong(p):
    polyList = degreePChebyPoly(p)
    return cheb.chebroots(polyList)

# This next one works
def degreePChebyPoints(p):
    print("degreePChebyPoints - start")
    polyList = degreePChebyPoly(p)
    polyListRev = list(reversed(polyList))
    roots = numpy.roots(polyListRev)
    roots.sort()
    print("degreePChebyPoints - end")
    return roots




In [24]:
a = degreePChebyPoints(3)
print(a)

[-0.8660254  0.         0.8660254]


In [101]:
degreePChebyPoly(3)

[0, -3, 0, 4]

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.integrate.quadrature.html

In [3]:
cheb.chebgauss(3)

(array([ 8.66025404e-01,  6.12323400e-17, -8.66025404e-01]),
 array([1.04719755, 1.04719755, 1.04719755]))

In [22]:
b = numpy.array([ 8.66025404e-01,  6.12323400e-17, -8.66025404e-01],dtype=float)
cheb.chebweight(b)


array([2., 1., 2.])

In [58]:
def func1(x):
    return (1 + math.cos(math.pi*x))**2

    
def chebyQuadrature(p):
    a = degreePChebyPoints(p)
    points, weights = cheb.chebgauss(p)
    res = 0.0
    for i in range(len(a)):
        res += weights[i] * func1(a[i])
    return res

In [62]:
chebyQuadrature(2)

0.4884315617262869

In [37]:
func1(0)

4.0

In [71]:
for i in range(1,35):
    print("{0}: {1}".format(i, chebyQuadrature(i)))

degreePChebyPoints - start
degreePChebyPoints - end
1: 12.566370614359172
degreePChebyPoints - start
degreePChebyPoints - end
2: 0.4884315617262869
degreePChebyPoints - start
degreePChebyPoints - end
3: 4.2047433496671625
degreePChebyPoints - start
degreePChebyPoints - end
4: 2.9077848669422526
degreePChebyPoints - start
degreePChebyPoints - end
5: 3.1788925872046074
degreePChebyPoints - start
degreePChebyPoints - end
6: 3.1440090915741576
degreePChebyPoints - start
degreePChebyPoints - end
7: 3.146957062288694
degreePChebyPoints - start
degreePChebyPoints - end
8: 3.1467816669009285
degreePChebyPoints - start
degreePChebyPoints - end
9: 3.14678941636617
degreePChebyPoints - start
degreePChebyPoints - end
10: 3.1467891517576345
degreePChebyPoints - start
degreePChebyPoints - end
11: 3.146789158956168
degreePChebyPoints - start
degreePChebyPoints - end
12: 3.1467891587963552
degreePChebyPoints - start
degreePChebyPoints - end
13: 3.146789158799312
degreePChebyPoints - start
degreePCheby

In [143]:
numpy.roots([1,0,-4])

array([-2.,  2.])

In [146]:
numpy.array([1,2],dtype=numpy.float)

array([1., 2.])

In [107]:
x = [1,3]
y = [1]


func = lambda x: 2 * x
pTerm2 = list(map(func, x))
print(pTerm2)
minusLists(x,y)

[2, 6]


[0, 3]

In [123]:
list(convertPolytoCheb([ 0.,  1.,  2.,  3.]))

[1.0, 3.25, 1.0, 0.75]

In [180]:
# Tried the following but doesn't work
def degreePChebyPoints3(p):
    polyList = degreePChebyPoly(p)
    polyListRev = list(reversed(polyList))
    chebSeries = convertPolytoCheb(polyListRev)
    return cheb.chebroots(chebSeries)

### Discussion for question 2.3

# Question 3: Root finding

Consider the function

$$F \left( x \right) = x^3 \cos \left( x \right) - \frac{x^3}{10}.$$

**3.1** Plot this function on the intervals $x \in \left[ -0.5, 1.5 \right]$ and $x \in \left[ -0.5, 5 \right]$. Use the SciPy `optimize.fsolve` function to find values for the roots of $F \left( x \right)$ in the interval $x \in \left[ -0.5, 5 \right]$.

Your code should be well laid out and easy to understand. Your plots should be appropriately formatted. You should make appropriate use of displayed output.

**[4 marks]**

In [ ]:
# Code for question 3.1

**3.2** Use Newton's method, and two other root finding methods, to seek the roots of $F \left( x \right)$ in the interval $x \in \left[ -0.5, 5 \right]$, identified in question 3.1.

Investigate the convergence properties of Newton's method for this problem, for each of the roots, and compare this against the convergence properties of the other methods.

Summarise and explain your results in a discussion of no more than 500 words.

Your code should be well laid out and easy to understand. You should make appropriate use of displayed output and plots.

**[15 marks]**

In [1]:
# Code for question 3.2

### Discussion for question 3.2